application: gphysicians
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/front.html
  upload: static/front.html

- url: /search
  static_files: static/search.html
  upload: static/search.html

- url: /api/.*
  script: api.app

- url: /
  static_dir: static


